import Link from 'next/link';
import { StatusChip } from '@/components/StatusChip';

export default function DashboardPage() {
  return <div className="home-dashboard">
    <div className="home-topline"><div><p className="eyebrow">NEXGEN / داشبورد رانندگی</p><h1>سلام، علی‌رضا <span>✦</span></h1><p>وضعیت دوربین و سفرهای شما در یک نگاه.</p></div><div className="home-actions"><StatusChip tone="amber">اپ موبایل متصل نیست</StatusChip><Link href="/settings" className="home-button">اتصال دستگاه <span>←</span></Link></div></div>
    <section className="hero-console"><div className="hero-copy"><StatusChip tone="violet">آماده برای ضبط</StatusChip><h2>جاده را از دست نده.</h2><p>دوربین را وصل کن تا ضبط حلقه‌ای، GPS و شناسایی پلاک هم‌زمان فعال شوند.</p><div className="hero-actions"><Link href="/settings" className="home-button primary">راه‌اندازی دوربین <span>←</span></Link><Link href="/trips" className="text-link">مشاهده آرشیو</Link></div></div><div className="console-visual"><div className="console-grid" /><div className="console-ring"><span>READY</span><b>۰۱</b></div><div className="console-readout"><span>GPS</span><strong>WAITING</strong><span>STORAGE</span><strong>۸ GB</strong></div></div></section>
    <section className="device-strip"><div className="privacy-note"><span>✓</span><div><strong>حریم خصوصی در اولویت</strong><small>ویدئو و تشخیص پلاک روی دستگاه پردازش می‌شود.</small></div></div><DeviceState label="کیفیت تصویر" value="1080p" tone="blue" /><DeviceState label="صدا" value="خاموش" tone="neutral" /><DeviceState label="GPS" value="فعال" tone="green" /><DeviceState label="ALPR" value="خاموش" tone="neutral" /></section>
    <div className="home-layout"><section><div className="section-heading"><div><p className="eyebrow">نمای کلی</p><h2>آمار دستگاه</h2></div><StatusChip tone="green">همه‌چیز پایدار</StatusChip></div><div className="home-stats"><Stat label="سفرها" value="۰" detail="هنوز سفری ثبت نشده" tone="violet" /><Stat label="زمان ضبط" value="۰ ساعت" detail="دوربین آماده نیست" tone="green" /><Stat label="پلاک‌ها" value="۰" detail="ALPR غیرفعال" tone="amber" /><Stat label="فضای مصرف‌شده" value="۰ گیگ" detail="از ۸ گیگابایت" tone="neutral" /></div></section><aside className="quick-panel"><div className="section-heading"><div><p className="eyebrow">دسترسی سریع</p><h2>ابزارها</h2></div></div><Link href="/trips" className="quick-item"><span className="quick-icon">▦</span><span><strong>آرشیو سفرها</strong><small>تقویم و مسیرها</small></span><b>←</b></Link><Link href="/messages" className="quick-item"><span className="quick-icon">⌁</span><span><strong>مرکز پیام</strong><small>هشدارها و اعلان‌های دستگاه</small></span><b>←</b></Link><Link href="/settings" className="quick-item"><span className="quick-icon">⚙</span><span><strong>تنظیمات حریم خصوصی</strong><small>همگام‌سازی و نگهداری داده</small></span><b>←</b></Link></aside></div>
    <section className="home-empty"><div><p className="eyebrow">فعالیت اخیر</p><h2>هنوز سفری شروع نشده</h2><p>بعد از اولین ضبط، مسیرها و رویدادهای مهم اینجا ظاهر می‌شوند.</p></div><Link href="/trips" className="text-link">رفتن به آرشیو <span>←</span></Link></section>
  </div>;
}

function DeviceState({ label, value, tone }: { label: string; value: string; tone: string }) { return <div className="device-state"><span className={`state-dot ${tone}`} /><div><small>{label}</small><strong>{value}</strong></div></div>; }
function Stat({ label, value, detail, tone }: { label: string; value: string; detail: string; tone: string }) { return <div className="home-stat"><div className={`stat-mark ${tone}`} /><p>{label}</p><strong>{value}</strong><small>{detail}</small></div>; }
