# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'NexGenDashCam' do
  use_frameworks! :linkage => :static

  pod 'React', :path => '../node_modules/react-native'
  pod 'React-Core', :path => '../node_modules/react-native/React'

  pod 'react-native-vision-camera', :path => '../node_modules/react-native-vision-camera'

  use_expo_modules!

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
        config.build_settings['ENABLE_BITCODE'] = 'NO'
        config.build_settings['SWIFT_VERSION'] = '5.9'
      end
    end
  end
end
