## Android project settings
android.useAndroidX=true
android.enableJetifier=false
org.gradle.jvmargs=-Xmx4G -XX:+HeapDumpOnOutOfMemoryError
org.gradle.parallel=true
org.gradle.configuration-cache=true

# React Native
reactNativeArchitectures=arm64-v8a,armeabi-v7a

newArchEnabled=true
hermesEnabled=true

# Kotlin
kotlin.code.style=official

# Publishing
nexgen.versionCode=1
nexgen.versionName=0.1.0
