'use client';

const TEXT = {
  "common.actions.logout": "Logout",
  "common.actions.back": "Back",
  "common.actions.create": "Create Email",
  "common.actions.saveChanges": "Save changes",
  "common.actions.saving": "Saving...",
  "common.actions.resetToDefaults": "Reset to Defaults",
  "common.actions.close": "Close",
  "common.actions.signingOut": "Signing out...",
  "common.actions.signedOutSuccess": "Signed out successfully!",
  "common.actions.signOutError": "Error signing out",
  "common.actions.refresh": "Refresh",
  "common.actions.loading": "Loading...",
  "common.actions.featureNotImplemented": "This feature is not implemented yet",
  "common.actions.moving": "Moving...",
  "common.actions.moved": "Moved",
  "common.actions.movedToInbox": "Moved to inbox",
  "common.actions.movingToInbox": "Moving to inbox...",
  "common.actions.movedToSpam": "Moved to spam",
  "common.actions.movingToSpam": "Moving to spam...",
  "common.actions.deletingMail": "Deleting mail...",
  "common.actions.failedToDeleteMail": "Failed to delete mail",
  "common.actions.deletedMail": "Mail deleted",
  "common.actions.archiving": "Archiving...",
  "common.actions.archived": "Archived",
  "common.actions.failedToMove": "Failed to move message",
  "common.actions.addingToFavorites": "Adding to favorites...",
  "common.actions.removingFromFavorites": "Removing from favorites...",
  "common.actions.addedToFavorites": "Added to favorites",
  "common.actions.removedFromFavorites": "Removed from favorites",
  "common.actions.failedToAddToFavorites": "Failed to add to favorites",
  "common.actions.failedToRemoveFromFavorites": "Failed to remove from favorites",
  "common.actions.failedToModifyFavorites": "Failed to modify favorites",
  "common.actions.movingToBin": "Moving to bin...",
  "common.actions.movedToBin": "Moved to bin",
  "common.actions.Bin": "Bin",
  "common.actions.failedToMoveToBin": "Failed to move to bin",
  "common.actions.markingAsRead": "Marking as read...",
  "common.actions.markingAsUnread": "Marking as unread...",
  "common.actions.hiddenImagesWarning": "Images are hidden by default for security reasons.",
  "common.actions.showImages": "Show Images",
  "common.actions.disableImages": "Hide Images",
  "common.actions.trustSender": "Trust Sender",
  "common.actions.cancel": "Cancel",
  "common.actions.save": "Save",
  "common.actions.remove": "Remove",
  "common.actions.settings": "Settings",
  "common.actions.exitSelectionModeEsc": "Click or press ESC to exit selection mode",
  "common.themes.dark": "Dark",
  "common.themes.light": "Light",
  "common.themes.system": "System",
  "common.commandPalette.title": "Command Palette",
  "common.commandPalette.description": "Quick navigation and actions for Mail-0",
  "common.commandPalette.placeholder": "Type a command or search...",
  "common.commandPalette.noResults": "No results found",
  "common.commandPalette.groups.mail": "Mail",
  "common.commandPalette.groups.settings": "Settings",
  "common.commandPalette.groups.actions": "Actions",
  "common.commandPalette.groups.help": "Help",
  "common.commandPalette.groups.navigation": "Navigation",
  "common.commandPalette.commands.goToInbox": "Go to Inbox",
  "common.commandPalette.commands.goToDrafts": "Go to Drafts",
  "common.commandPalette.commands.goToSent": "Go to Sent",
  "common.commandPalette.commands.goToSpam": "Go to Spam",
  "common.commandPalette.commands.goToArchive": "Go to Archive",
  "common.commandPalette.commands.goToBin": "Go to Bin",
  "common.commandPalette.commands.goToSettings": "Go to Settings",
  "common.commandPalette.commands.newEmail": "New Email",
  "common.commandPalette.commands.composeMessage": "New Email",
  "common.commandPalette.commands.searchEmails": "Search Emails",
  "common.commandPalette.commands.toggleTheme": "Toggle Theme",
  "common.commandPalette.commands.backToMail": "Back to Mail",
  "common.commandPalette.commands.goToDocs": "Go to docs",
  "common.commandPalette.commands.helpWithShortcuts": "Help with shortcuts",
  "common.commandPalette.commands.commandPalette": "Command Palette",
  "common.searchBar.pickDateRange": "Pick a date or a range",
  "common.searchBar.search": "Search",
  "common.searchBar.clearSearch": "Clear search",
  "common.searchBar.advancedSearch": "Advanced search",
  "common.searchBar.quickFilters": "Quick filters",
  "common.searchBar.searchIn": "Search in",
  "common.searchBar.recipient": "Recipient",
  "common.searchBar.sender": "Sender",
  "common.searchBar.subject": "Subject",
  "common.searchBar.from": "From",
  "common.searchBar.dateRange": "Date range",
  "common.searchBar.category": "Category",
  "common.searchBar.folder": "Folder",
  "common.searchBar.allMail": "All Mail",
  "common.searchBar.unread": "Unread",
  "common.searchBar.hasAttachment": "Has Attachment",
  "common.searchBar.starred": "Starred",
  "common.searchBar.applyFilters": "Apply filters",
  "common.searchBar.reset": "Reset",
  "common.searchBar.searching": "Searching...",
  "common.searchBar.aiSuggestions": "AI Suggestions",
  "common.searchBar.aiSearching": "AI is searching...",
  "common.searchBar.aiSearchError": "AI search failed. Please try again.",
  "common.searchBar.aiNoResults": "No AI suggestions found",
  "common.searchBar.aiEnhancedQuery": "Enhanced search query",
  "common.navUser.customerSupport": "Community",
  "common.navUser.documentation": "Documentation",
  "common.navUser.appTheme": "App Theme",
  "common.navUser.accounts": "Accounts",
  "common.navUser.signIn": "Sign in",
  "common.navUser.otherAccounts": "Other Accounts",
  "common.mailCategories.primary": "Primary",
  "common.mailCategories.allMail": "All Mail",
  "common.mailCategories.important": "Important",
  "common.mailCategories.personal": "Personal",
  "common.mailCategories.updates": "Updates",
  "common.mailCategories.promotions": "Promotions",
  "common.mailCategories.social": "Social",
  "common.mailCategories.unread": "Unread",
  "common.replyCompose.replyTo": "Reply to",
  "common.replyCompose.thisEmail": "this email",
  "common.replyCompose.dropFiles": "Drop files to attach",
  "common.replyCompose.attachments": "Attachments",
  "common.replyCompose.attachmentCount": "{count, plural, =0 {attachments} one {attachment} other {attachments}}",
  "common.replyCompose.fileCount": "{count, plural, =0 {files} one {file} other {files}}",
  "common.replyCompose.saveDraft": "Save draft",
  "common.replyCompose.send": "Send",
  "common.replyCompose.forward": "Forward",
  "common.mailDisplay.details": "Details",
  "common.mailDisplay.from": "From",
  "common.mailDisplay.to": "To",
  "common.mailDisplay.cc": "Cc",
  "common.mailDisplay.bcc": "Bcc",
  "common.mailDisplay.date": "Date",
  "common.mailDisplay.mailedBy": "Mailed-By",
  "common.mailDisplay.signedBy": "Signed-By",
  "common.mailDisplay.security": "Security",
  "common.mailDisplay.standardEncryption": "Standard encryption (TLS)",
  "common.mailDisplay.loadingMailContent": "Loading mail content...",
  "common.mailDisplay.unsubscribe": "Unsubscribe",
  "common.mailDisplay.unsubscribed": "Unsubscribed",
  "common.mailDisplay.unsubscribeDescription": "Are you sure you want to unsubscribe from this mailing list?",
  "common.mailDisplay.unsubscribeOpenSiteDescription": "To stop getting messages from this mailing list, go to their website to unsubscribe.",
  "common.mailDisplay.cancel": "Cancel",
  "common.mailDisplay.goToWebsite": "Go to website",
  "common.mailDisplay.failedToUnsubscribe": "Failed to unsubscribe from mailing list",
  "common.threadDisplay.exitFullscreen": "Exit fullscreen",
  "common.threadDisplay.enterFullscreen": "Enter fullscreen",
  "common.threadDisplay.archive": "Archive",
  "common.threadDisplay.reply": "Reply",
  "common.threadDisplay.moreOptions": "More options",
  "common.threadDisplay.moveToSpam": "Move to Spam",
  "common.threadDisplay.replyAll": "Reply all",
  "common.threadDisplay.forward": "Forward",
  "common.threadDisplay.markAsUnread": "Mark as Unread",
  "common.threadDisplay.markAsRead": "Mark as Read",
  "common.threadDisplay.addLabel": "Add label",
  "common.threadDisplay.muteThread": "Mute thread",
  "common.threadDisplay.favourites": "Favourites",
  "common.threadDisplay.disableImages": "Hide Images",
  "common.threadDisplay.enableImages": "Show Images",
  "common.threadDisplay.star": "Star",
  "common.threadDisplay.unstar": "Unstar",
  "common.notes.title": "Notes",
  "common.notes.empty": "No notes for this email",
  "common.notes.emptyDescription": "Add notes to keep track of important information or follow-ups.",
  "common.notes.addNote": "Add a note",
  "common.notes.addYourNote": "Add your note here...",
  "common.notes.editNote": "Edit note",
  "common.notes.deleteNote": "Delete note",
  "common.notes.deleteConfirm": "Are you sure you want to delete this note?",
  "common.notes.deleteConfirmDescription": "This action cannot be undone.",
  "common.notes.cancel": "Cancel",
  "common.notes.delete": "Delete",
  "common.notes.save": "Save note",
  "common.notes.toSave": "to save",
  "common.notes.label": "Label:",
  "common.notes.search": "Search notes...",
  "common.notes.noteCount": "{count, plural, =0 {Add notes} one {# note} other {# notes}}",
  "common.notes.notePinned": "Note pinned",
  "common.notes.noteUnpinned": "Note unpinned",
  "common.notes.colorChanged": "Note color updated",
  "common.notes.noteUpdated": "Note updated",
  "common.notes.noteDeleted": "Note deleted",
  "common.notes.noteCopied": "Copied to clipboard",
  "common.notes.noteAdded": "Note added",
  "common.notes.notesReordered": "Notes reordered",
  "common.notes.noMatchingNotes": "No notes matching \"{query}\"",
  "common.notes.clearSearch": "Clear search",
  "common.notes.pinnedNotes": "Pinned notes",
  "common.notes.otherNotes": "Other notes",
  "common.notes.created": "Created",
  "common.notes.updated": "Updated",
  "common.notes.errors.failedToLoadNotes": "Failed to load notes",
  "common.notes.errors.failedToLoadThreadNotes": "Failed to load thread notes",
  "common.notes.errors.failedToAddNote": "Failed to add note",
  "common.notes.errors.failedToUpdateNote": "Failed to update note",
  "common.notes.errors.failedToDeleteNote": "Failed to delete note",
  "common.notes.errors.failedToUpdateNoteColor": "Failed to update note color",
  "common.notes.errors.noValidNotesToReorder": "No valid notes to reorder",
  "common.notes.errors.failedToReorderNotes": "Failed to reorder notes",
  "common.notes.colors.default": "Default",
  "common.notes.colors.red": "Red",
  "common.notes.colors.orange": "Orange",
  "common.notes.colors.yellow": "Yellow",
  "common.notes.colors.green": "Green",
  "common.notes.colors.blue": "Blue",
  "common.notes.colors.purple": "Purple",
  "common.notes.colors.pink": "Pink",
  "common.notes.actions.pin": "Pin note",
  "common.notes.actions.unpin": "Unpin note",
  "common.notes.actions.edit": "Edit note",
  "common.notes.actions.delete": "Delete note",
  "common.notes.actions.copy": "Copy note",
  "common.notes.actions.changeColor": "Change color",
  "common.settings.notFound": "Settings not found",
  "common.settings.saved": "Settings saved",
  "common.settings.failedToSave": "Failed to save settings",
  "common.settings.languageChanged": "Language changed to {locale}",
  "common.mail.replies": "{count, plural, =0 {replies} one {# reply} other {# replies}}",
  "common.mail.deselectAll": "Deselected all emails",
  "common.mail.selectedEmails": "Selected {count} emails",
  "common.mail.noEmailsToSelect": "No emails to select",
  "common.mail.markedAsRead": "Marked as read",
  "common.mail.markedAsUnread": "Marked as unread",
  "common.mail.failedToMarkAsRead": "Failed to mark as read",
  "common.mail.failedToMarkAsUnread": "Failed to mark as unread",
  "common.mail.selected": "{count} selected",
  "common.mail.clearSelection": "Clear Selection",
  "common.mail.moveToSpam": "Move to Spam",
  "common.mail.moveToInbox": "Move to Inbox",
  "common.mail.deleteFromBin": "Delete from Bin",
  "common.mail.unarchive": "Unarchive",
  "common.mail.archive": "Archive",
  "common.mail.moveToBin": "Move to Bin",
  "common.mail.restoreFromBin": "Restore from Bin",
  "common.mail.markAsUnread": "Mark as Unread",
  "common.mail.markAsRead": "Mark as Read",
  "common.mail.addFavorite": "Favorite",
  "common.mail.removeFavorite": "Unfavorite",
  "common.mail.muteThread": "Mute Thread",
  "common.mail.moving": "Moving...",
  "common.mail.moved": "Moved",
  "common.mail.errorMoving": "Error moving",
  "common.mail.reply": "Reply",
  "common.mail.replyAll": "Reply All",
  "common.mail.forward": "Forward",
  "common.mail.labels": "Labels",
  "common.mail.createNewLabel": "Create New Label",
  "common.mail.noLabelsAvailable": "No labels available",
  "common.mail.loadMore": "Load more",
  "common.mail.imagesHidden": "Images are hidden for security reasons",
  "common.mail.showImages": "Show Images",
  "common.mail.noEmails": "No emails available",
  "common.mail.noSearchResults": "No search results found",
  "common.mail.clearSearch": "Clear search",
  "common.mail.markAsImportant": "Mark as Important",
  "common.mail.unSubscribeFromAll": "Unsubscribe from all",
  "common.mail.starAll": "Star all",
  "common.mail.mute": "Mute",
  "common.mail.unmute": "Unmute",
  "common.mail.muted": "Muted",
  "common.mail.failedToMute": "Failed to mute",
  "common.mail.failedToUnmute": "Failed to unmute",
  "common.mail.archived": "Archived",
  "common.mail.failedToArchive": "Failed to archive",
  "common.units.mb": "{amount} MB",
  "common.labels.deleteLabel": "Delete Label",
  "common.labels.deleteLabelConfirm": "Are you sure you want to delete this label?",
  "common.labels.deleteLabelConfirmDescription": "This action cannot be undone.",
  "common.labels.deleteLabelConfirmCancel": "Cancel",
  "common.labels.deleteLabelConfirmDelete": "Delete",
  "common.labels.deleteLabelSuccess": "Label deleted successfully",
  "navigation.sidebar.inbox": "Inbox",
  "navigation.sidebar.drafts": "Drafts",
  "navigation.sidebar.sent": "Sent",
  "navigation.sidebar.spam": "Spam",
  "navigation.sidebar.archive": "Archive",
  "navigation.sidebar.bin": "Bin",
  "navigation.sidebar.feedback": "Feedback",
  "navigation.sidebar.settings": "Settings",
  "navigation.settings.general": "General",
  "navigation.settings.connections": "Connections",
  "navigation.settings.security": "Security",
  "navigation.settings.appearance": "Appearance",
  "navigation.settings.signatures": "Signatures",
  "navigation.settings.shortcuts": "Shortcuts",
  "navigation.settings.labels": "Labels",
  "navigation.settings.dangerZone": "Danger Zone",
  "navigation.settings.deleteAccount": "Delete Account",
  "navigation.settings.privacy": "Privacy",
  "pages.error.notFound.title": "Page Not Found",
  "pages.error.notFound.description": "Oops! The page you're looking for doesn't exist or has been moved.",
  "pages.error.notFound.goBack": "Go Back",
  "pages.error.settingsNotFound": "404 - Settings page not found",
  "pages.settings.general.title": "General",
  "pages.settings.general.description": "Manage settings for your language and email display preferences.",
  "pages.settings.general.language": "Language",
  "pages.settings.general.selectLanguage": "Select a language",
  "pages.settings.general.timezone": "Timezone",
  "pages.settings.general.selectTimezone": "Select a timezone",
  "pages.settings.general.dynamicContent": "Dynamic Content",
  "pages.settings.general.dynamicContentDescription": "Allow emails to display dynamic content.",
  "pages.settings.general.languageChangedTo": "Language changed to {locale}",
  "pages.settings.general.customPrompt": "Custom AI Prompt",
  "pages.settings.general.customPromptPlaceholder": "Enter your custom prompt for the AI...",
  "pages.settings.general.customPromptDescription": "Customize how the AI writes your email replies. This will be added to the base prompt.",
  "pages.settings.general.noResultsFound": "No results found",
  "pages.settings.connections.title": "Email Connections",
  "pages.settings.connections.description": "Connect your email accounts to Orbit.",
  "pages.settings.connections.disconnectTitle": "Disconnect Email Account",
  "pages.settings.connections.disconnectDescription": "Are you sure you want to disconnect this email?",
  "pages.settings.connections.cancel": "Cancel",
  "pages.settings.connections.remove": "Remove",
  "pages.settings.connections.disconnectSuccess": "Account disconnected successfully",
  "pages.settings.connections.disconnectError": "Failed to disconnect account",
  "pages.settings.connections.addEmail": "Add Connection",
  "pages.settings.connections.connectEmail": "Connect Email",
  "pages.settings.connections.connectEmailDescription": "Select an email provider to connect",
  "pages.settings.connections.moreComingSoon": "More coming soon",
  "pages.settings.connections.reconnect": "Reconnect",
  "pages.settings.connections.disconnected": "Disconnected",
  "pages.settings.security.title": "Security",
  "pages.settings.security.description": "Manage your security preferences and account protection.",
  "pages.settings.security.twoFactorAuth": "Two-Factor Authentication",
  "pages.settings.security.twoFactorAuthDescription": "Add an extra layer of security to your account",
  "pages.settings.security.loginNotifications": "Login Notifications",
  "pages.settings.security.loginNotificationsDescription": "Get notified about new login attempts",
  "pages.settings.security.deleteAccount": "Delete Account",
  "pages.settings.security.loadImagesDefault": "Load Images by Default",
  "pages.settings.security.loadImagesDefaultDescription": "Images are not loaded by default for security reasons.",
  "pages.settings.appearance.title": "Appearance",
  "pages.settings.appearance.description": "Customize colors, fonts and view options.",
  "pages.settings.appearance.theme": "Theme",
  "pages.settings.appearance.inboxType": "Inbox Type",
  "pages.settings.signatures.title": "Email Signatures",
  "pages.settings.signatures.description": "Create and manage your email signature that appears at the bottom of your messages.",
  "pages.settings.signatures.enableSignature": "Enable signature",
  "pages.settings.signatures.enableSignatureDescription": "Add your signature to the end of all outgoing messages.",
  "pages.settings.signatures.includeByDefault": "Include by default",
  "pages.settings.signatures.includeByDefaultDescription": "Automatically add your signature when composing new emails.",
  "pages.settings.signatures.signatureContent": "Signature Content",
  "pages.settings.signatures.signatureContentPlaceholder": "Create your signature with formatting, links, and images.",
  "pages.settings.signatures.signaturePreview": "Signature Preview",
  "pages.settings.signatures.signatureSaved": "Signature saved successfully",
  "pages.settings.signatures.signaturePreviewDescription": "This is how your signature will appear in emails.",
  "pages.settings.signatures.editorType": "Editor Type",
  "pages.settings.signatures.editorTypeDescription": "Choose between plain text/HTML input or a rich text editor for your signature.",
  "pages.settings.signatures.plainText": "Plain Text / HTML",
  "pages.settings.signatures.richText": "Rich Text Editor",
  "pages.settings.signatures.richTextDescription": "Use the rich text editor to format your signature.",
  "pages.settings.signatures.richTextPlaceholder": "Format your signature with the rich text editor...",
  "pages.settings.signatures.signatureContentHelp": "You can use HTML to add formatting, links, and images to your signature.",
  "pages.settings.shortcuts.title": "Keyboard Shortcuts",
  "pages.settings.shortcuts.description": "View and customize keyboard shortcuts for quick actions.",
  "pages.settings.shortcuts.actions.newEmail": "New Email",
  "pages.settings.shortcuts.actions.sendEmail": "Send Email",
  "pages.settings.shortcuts.actions.reply": "Reply",
  "pages.settings.shortcuts.actions.replyAll": "Reply All",
  "pages.settings.shortcuts.actions.forward": "Forward",
  "pages.settings.shortcuts.actions.drafts": "Go to drafts",
  "pages.settings.shortcuts.actions.inbox": "Go to inbox",
  "pages.settings.shortcuts.actions.sentMail": "Go to sent mail",
  "pages.settings.shortcuts.actions.delete": "Delete",
  "pages.settings.shortcuts.actions.search": "Search",
  "pages.settings.shortcuts.actions.markAsUnread": "Mark as unread",
  "pages.settings.shortcuts.actions.muteThread": "Mute thread",
  "pages.settings.shortcuts.actions.printEmail": "Print Email",
  "pages.settings.shortcuts.actions.archiveEmail": "Archive Thread",
  "pages.settings.shortcuts.actions.markAsSpam": "Mark as Spam",
  "pages.settings.shortcuts.actions.moveToFolder": "Move to Folder",
  "pages.settings.shortcuts.actions.undoLastAction": "Undo Last Action",
  "pages.settings.shortcuts.actions.viewEmailDetails": "View Email Details",
  "pages.settings.shortcuts.actions.goToDrafts": "Go to Drafts",
  "pages.settings.shortcuts.actions.expandEmailView": "Expand Email View",
  "pages.settings.shortcuts.actions.helpWithShortcuts": "Help with shortcuts",
  "pages.settings.shortcuts.actions.recordHotkey": "Record Hotkey",
  "pages.settings.shortcuts.actions.pressKeys": "Press keys",
  "pages.settings.shortcuts.actions.releaseKeys": "Release keys",
  "pages.settings.shortcuts.actions.selectAll": "Select All",
  "pages.settings.shortcuts.actions.commandPalette": "Command Palette",
  "pages.settings.shortcuts.actions.markAsRead": "Mark as Read",
  "pages.settings.shortcuts.actions.exitSelectionMode": "Exit Selection Mode",
  "pages.settings.shortcuts.actions.closeCompose": "Close compose",
  "pages.settings.shortcuts.actions.goToSpam": "Go to Spam",
  "pages.settings.shortcuts.actions.goToArchive": "Go to Archive",
  "pages.settings.shortcuts.actions.goToBin": "Go to Bin",
  "pages.settings.shortcuts.actions.scrollDown": "Scroll down in mail list",
  "pages.settings.shortcuts.actions.scrollUp": "Scroll up in mail list",
  "pages.settings.shortcuts.actions.goToSettings": "Go to Settings",
  "pages.settings.shortcuts.actions.showImportant": "Show important",
  "pages.settings.shortcuts.actions.showAllMail": "Show all mail",
  "pages.settings.shortcuts.actions.showPersonal": "Show personal",
  "pages.settings.shortcuts.actions.showUpdates": "Show updates",
  "pages.settings.shortcuts.actions.showPromotions": "Show promotions",
  "pages.settings.shortcuts.actions.showUnread": "Show unread",
  "pages.settings.shortcuts.actions.selectUnderCursor": "Select under cursor",
  "pages.settings.labels.title": "Labels",
  "pages.settings.labels.description": "Manage your labels for better organization of your emails.",
  "pages.settings.dangerZone.title": "Danger Zone",
  "pages.settings.dangerZone.description": "Permanently delete your account and all associated data.",
  "pages.settings.dangerZone.warning": "This action cannot be undone.",
  "pages.settings.dangerZone.confirmation": "Please type DELETE to confirm account deletion",
  "pages.settings.dangerZone.deleteAccount": "Delete Account",
  "pages.settings.dangerZone.deleting": "Deleting...",
  "pages.settings.dangerZone.deleted": "Account deleted successfully",
  "pages.settings.dangerZone.error": "Failed to delete account",
  "pages.settings.privacy.title": "Privacy",
  "pages.settings.privacy.description": "Manage your privacy and security preferences for email content.",
  "pages.settings.privacy.externalImages": "Display External Images",
  "pages.settings.privacy.externalImagesDescription": "Allow emails to display images from external sources.",
  "pages.settings.privacy.trustedSenders": "Trusted Senders",
  "pages.settings.privacy.trustedSendersDescription": "Always display images for these senders.",
  "pages.createEmail.invalidEmail": "Invalid email address",
  "pages.createEmail.body": "Body",
  "pages.createEmail.example": "orbit@orbit.email",
  "pages.createEmail.attachments": "Attachments ({count})",
  "pages.createEmail.addMore": "Add more",
  "pages.createEmail.dropFilesToAttach": "Drop files to attach",
  "pages.createEmail.writeYourMessageHere": "Write your message here...",
  "pages.createEmail.emailSent": "Email sent",
  "pages.createEmail.emailSentSuccessfully": "Email sent successfully",
  "pages.createEmail.failedToSendEmail": "Failed to send email. Please try again.",
  "pages.createEmail.signature.title": "Signature",
  "pages.createEmail.signature.include": "Include signature",
  "pages.createEmail.signature.remove": "Remove signature",
  "pages.createEmail.signature.enable": "Enable signature",
  "pages.createEmail.signature.disable": "Disable signature",
  "pages.createEmail.signature.add": "Add signature",
  "pages.createEmail.addLink": "Add Link",
  "pages.createEmail.addUrlToCreateALink": "Add URL to create a link. The link will open in a new tab.",
  "pages.createEmail.editor.menuBar.heading1": "Heading 1",
  "pages.createEmail.editor.menuBar.heading2": "Heading 2",
  "pages.createEmail.editor.menuBar.heading3": "Heading 3",
  "pages.createEmail.editor.menuBar.bold": "Bold",
  "pages.createEmail.editor.menuBar.italic": "Italic",
  "pages.createEmail.editor.menuBar.strikethrough": "Strikethrough",
  "pages.createEmail.editor.menuBar.underline": "Underline",
  "pages.createEmail.editor.menuBar.link": "Link",
  "pages.createEmail.editor.menuBar.bulletList": "Bullet List",
  "pages.createEmail.editor.menuBar.orderedList": "Ordered List",
  "pages.createEmail.editor.menuBar.viewAttachments": "View Attachments",
  "pages.createEmail.editor.menuBar.attachFiles": "Attach Files",
  "errorMessages.required_scopes_missing": "We’re missing the permissions needed to craft your full experience. Please sign in again and allow the requested access.",
  "errorMessages.early_access_required": "Early access is required to log in",
  "errorMessages.unauthorized": "Orbit could not load your data from the 3rd party provider. Please try again."
} as const;

type Values = Record<string, string | number | boolean | null | undefined>;

const humanize = (key: string) =>
  key
    .split('.')
    .pop()!
    .replace(/([a-z])([A-Z])/g, '$1 $2')
    .replace(/[-_]/g, ' ')
    .replace(/^./, (char) => char.toUpperCase());

const interpolate = (text: string, values?: Values) => {
  if (!values) return text;
  return text.replace(/\{(\w+)\}/g, (_, key: string) => String(values[key] ?? ''));
};

export type MessageKey = keyof typeof TEXT | string;

export function translate(key: MessageKey, values?: Values) {
  return interpolate(TEXT[key as keyof typeof TEXT] ?? humanize(String(key)), values);
}

export function useTranslations() {
  return translate;
}

export function useLocale() {
  return 'en';
}

export function useFormatter() {
  return {
    dateTime(date: Date | string | number, options?: Intl.DateTimeFormatOptions) {
      return new Intl.DateTimeFormat('en', options).format(new Date(date));
    },
    relativeTime(value: number, unit: Intl.RelativeTimeFormatUnit, options?: Intl.RelativeTimeFormatOptions) {
      return new Intl.RelativeTimeFormat('en', options).format(value, unit);
    },
  };
}
